# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # ========== BOOT ==========
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/58ab5e9a-0727-46b9-8c88-6d65ad7c2f74";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D850-C90D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/pg_data" = {
    device = "/dev/disk/by-uuid/05cd27fb-a59c-4766-ba60-0404b217acab";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };

  fileSystems."/backup" = {
    device = "/dev/disk/by-uuid/9b9dbb79-07bd-445b-88dc-2c807cdb47da";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/d2a2b746-47d1-423e-a8c1-19d62a4ed313"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
